name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Scala
      uses: japgolly/setup-everything-scala@v3.1
    - name: Build and test
      run: sbt "frontend/compile"
